Repository Team-WSS/WSS-iOS, pull requests merged in 2024-12, with the labels that each got.

#373 [Feat] #372 - 피드상세뷰 내 프로필 클릭 이벤트 추가 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
Labels: guryss, reviewPlz

#379 [Fix] #378 - 카카오톡 설치 안된 경우 카카오 계정 로그인 되도록 구현
  WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
Labels: nagi, reviewPlz

#381 [Setting] #380 - 프로비저닝 파일 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
Labels: e-na, reviewPlz

#377 [Fix] #367 - MyPage 전반적인 수정
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewModel/FeedGenreViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryChildView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryPageBar.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryChildViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryChildViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageLibraryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageFeedEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageNovelPreferencesView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPagePreferencesEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPagePrivateView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageEditProfileViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageEditProfileViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageFeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageProfileVisibilityViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageSettingViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageInfoViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageProfileVisibilityViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedCell/NovelDetailFeedTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: e-na, reviewPlz

#383 [Fix] #382 - 홈뷰 취향추천 컬렉션뷰의 높이 동적 조절 반영
  .github/pull_request_template.md
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeTasteRecommendView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
Labels: guryss, reviewPlz

#385 [Setting] #384 - Config 분리하여 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
Labels: e-na, veryGoodDeveloper

#390 [Chore] #389 - 공지사항 텍스트 하이퍼링크 기능 구현
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailView/HomeNoticeDetailAssistantView/HomeNoticeDetailContentView.swift
Labels: guryss, reviewPlz

#394 [Fix] #393 - UILabel 이모지 깨지는 문제 해결
  WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
Labels: haku, reviewPlz

#391 [Feat] #387 - 앱 최소버전보다 작을 시 앱 강제 업데이트 기능 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/AppVersionResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/AlertButton/WSSAlertViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
Labels: guryss, reviewPlz

#400 [Fix] #399 - 수다글 엔터 키 입력 시 커서가 맨 끝으로 이동하는 문제 해결
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
Labels: haku, reviewPlz

#392 [Fix] #388 - 보관함 에러 수정
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryChildViewModel.swift
Labels: e-na, veryGoodDeveloper
