Repository Team-WSS/WSS-iOS, pull requests merged in 2024-10, with the labels that each got.

#287 [Fix] #286 - Dropdown 오류 수정 (+Dropdown 사용방법)
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/Base/Dropdown/WSSDropdownButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/Dropdown/WSSDropdownManager.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
Labels: e-na, veryGoodDeveloper

#293 [Design] #191 - 상세탐색뷰 내 DetailSearchKeywordView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchBottomView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchKeywordView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
Labels: guryss, reviewPlz

#295 [Network] #248 - 피드상세뷰 내 드롭다운 UI 구현 및 API 연결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Feed/FeedDetailService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Feed/icReportCheck.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Feed/icReportCheck.imageset/icReportCheck.svg
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedDetailRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailDropdownView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
Labels: guryss, reviewMore

#298 [Fix] #297 - NormalSearch UI 수정 및 Cell 클릭 시 작품상세뷰로 이동
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
Labels: guryss, reviewMore

#296 [Network] #252 - 댓글 작성 API 및 피드 상세뷰 UI 수정
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Feed/FeedDetailService.swift
  WSSiOS/WSSiOS/Network/Search/SearchService.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Data/DTO/FeedDetailResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedDetailRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedAssistantView/FeedReactView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyWritingView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
Labels: guryss, reviewMore
