Repository Team-WSS/WSS-iOS, pull requests merged in 2024-07, with the labels that each got.

#173 [Fix] #172 - HomeView 내 applyWSSFont 메서드 적용
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeInterestView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeTasteRecommendView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeTodayPopularView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeUnregisterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTasteRecommendCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTodayPopularCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
Labels: chetseoo, reviewPlz

#159 [Design] #158 - SearchView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icSearch.imageset/icSearch.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/icSearch.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/icSearch.imageset/icSearch.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/icTextPick!.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/icTextPick!.imageset/icTextPick!.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/imgInduceSearchDetail.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/imgInduceSearchDetail.imageset/imgInduceSearchDetail.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/imgInduceSearchDetail.imageset/imgInduceSearchDetail@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/imgInduceSearchDetail.imageset/imgInduceSearchDetail@3x.png
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/DTO/SearchResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/SearchRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchBarView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchDetailInduceView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchSosoPickView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SosoPickCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewModel/SearchViewModel.swift
  WSSiOS/WSSiOS/Trash/SearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Trash/SearchEmptyView.swift
  WSSiOS/WSSiOS/Trash/SearchHeaderView.swift
  WSSiOS/WSSiOS/Trash/SearchResultView.swift
Labels: chetseoo, reviewMore

#170 [Design] #160 - NormalSearchView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Color/WSSGray200.colorset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgEmpty.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgEmpty.imageset/imgEmpty.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgEmpty.imageset/imgEmpty@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgEmpty.imageset/imgEmpty@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icNavigateLeft.imageset/icNavigateLeft.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icSearchCancel.imageset/icSearchCancel.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Search/icSearch.imageset/icSearch.svg
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/SearchResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/SearchRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalAssistantView/NormalSearchEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalAssistantView/NormalSearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalAssistantView/NormalSearchResultCountView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalAssistantView/NormalSearchResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalSearchCell/NormalSearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalSearchView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/Search/SearchAssistantView/SearchBarView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/Search/SearchAssistantView/SearchDetailInduceView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/Search/SearchAssistantView/SearchSosoPickView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/Search/SearchCell/SosoPickCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/Search/SearchView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/NormalSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewModel/NormalSearchViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewModel/SearchViewModel.swift
Labels: chetseoo, reviewMore

#163 [Design] #148 - HomeView UI 2차 구현 (공지사항뷰, 로그인 유도 모달뷰)
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/adminProfileImage.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/adminProfileImage.imageset/adminProfileImage.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/adminProfileImage.imageset/adminProfileImage@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/adminProfileImage.imageset/adminProfileImage@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgInduceLogin.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgInduceLogin.imageset/imgInduceLogin.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgInduceLogin.imageset/imgInduceLogin@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgInduceLogin.imageset/imgInduceLogin@3x.png
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NoticeResult.swift
  WSSiOS/WSSiOS/Source/Data/DTO/RecommendResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NoticeRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeInduceLoginModalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeRealtimePopularContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeUnregisterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeNoticeTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeRealtimePopularContentTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeNoticeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeNoticeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewModel/HomeNoticeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewModel/HomeViewModel.swift
Labels: chetseoo, reviewMore

#175 [Design] #169 - NovelDetail TabBar UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailHeaderView/NovelDetailHeaderAssistantView/NovelDetailLargeCoverImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailTabBarView/NovelDetailTabBarView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewModel/NovelDetailViewModel.swift
Labels: naknak, reviewMore

#185 [Design] #184 - 공용컴포넌트 AlertButton 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Alert/icAlertWarningCircle.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Alert/icAlertWarningCircle.imageset/icon-warning-circle.svg
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/AlertButton/WSSAlertButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/AlertButton/WSSAlertViewController.swift
Labels: e-na, reviewMore

#188 [Fix] #187 - NormalSearchCollectionViewCell의 titleLabel 동적 높이 조절 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIFont+.swift
  WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/SearchRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTasteRecommendCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTodayPopularCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/NormalSearch/NormalSearchCell/NormalSearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/NormalSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewModel/NormalSearchViewModel.swift
Labels: chetseoo, reviewMore

#162 [Design] #161 - MyPage View 구조 세팅 및 Header UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/imgEmptyCat.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/imgEmptyCat.imageset/imgEmptyCat-2.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/pencil.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/pencil.imageset/pencil-3.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/setting.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/MyPage/setting.imageset/Vector.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icDropDownDot.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icDropDownDot.imageset/Frame 1321318326.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icDropDownDot.imageset/three-dots.svg
  WSSiOS/WSSiOS/Source/Data/DTO/MyProfileResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/Dropdown/WSSDropdownButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/Dropdown/WSSDropdownManager.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageProfileHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageCell/MyPageSettingCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageChangeNicknameView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageCustomModalView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageCustomModalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageModalAvatarFeatureLabelView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageSettingView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageTallyReuseView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/NoExist/MyPageTallyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageChangeNickNameViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageViewModel.swift
Labels: e-na, reviewMore
