Repository Team-WSS/WSS-iOS, pull requests merged in 2024-02, with the labels that each got.

#114 [Setting] #113 - TestToken 추가
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
  WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
Labels: e-na, reviewPlz

#117 [Refactor] #111 - RecordView Refactor
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/exampleAvater.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/exampleAvater.imageset/exampleAvatar.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/render.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/render.imageset/render.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample1.imageset/3.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample1.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample3.imageset/3-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample3.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample4.imageset/3-3.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample4.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample5.imageset/3-4.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample5.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample6.imageset/3-5.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sample6.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sosopickSampleImage.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Dummy/sosopickSampleImage.imageset/sa.png
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UITableViewCell+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderAlignmentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
Labels: chetseoo, reviewMore

#116 [Refactor] #111 - RegisterNormalView Refactor
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Loading/imgLoadingBanner.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Loading/imgLoadingBanner.imageset/imgLoadingBackground.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Loading/imgLoadingBanner.imageset/imgLoadingBackground@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Loading/imgLoadingBanner.imageset/imgLoadingBackground@3x.png
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/Base/ReadStatus.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSSectionTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalBannerImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePicker.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePickerButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDividerView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoWithRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalStarRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalToggleButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewPlz

#118 [Refactor] #111 - RegisterSuccessView Refactor
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewPlz

#119 [Refactor] #111 - NovelDetailView Refactor
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailCreateMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoGenreView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoKeywordView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoSettingButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailTabView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoKeywordCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoPlatformCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
Labels: hyowon, reviewPlz

#121 [Refactor] #111 - LibraryView Refactor
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryPageBar.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
Labels: e-na, reviewPlz

#123 [Refactor] #111 - Refactor LibraryView and MyPageView
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSSectionTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageModalAvatarFeatureLabelView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageSettingView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyReuseView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageChangeNicknameView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCustomModalView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
Labels: e-na

#122 [Refactor] #111 - MemoView Refactor
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoReadContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoEditView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoReadView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: hyowon, reviewPlz

#120 [Refactor] #111 - SearchView Refactor
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/DTO/SearchResult.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
Labels: chetseoo, reviewMore

#124 [Refactor] #111 - DeletePopupView Refactor
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
Labels: hyowon, reviewPlz

#127 [Setting] #125 - ViewModelType 프로토콜 추가
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/Base/Protocol/ViewModelType.swift
Labels: e-na, reviewPlz

#126 [Design] #111 - RegisterNormalView UI관련 추가 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalBannerImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePicker.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDifferentRadiusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDividerView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoWithRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalToggleButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewMore

#128 [Refactor] #125 - RegisterView MVVM Refactor
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Constants/Factory/ModuleFactory.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalVeiwModel/RegisterNormalViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalVeiwModel/RegisterViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
Labels: naknak, reviewMore
