Repository Team-WSS/WSS-iOS, pull requests merged in 2024-05, with the labels that each got.

#146 [Design] #145 - TabBar UI 수정
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateFeed.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateFeed.imageset/icNavigateFeed.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateFeedSelected.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateFeedSelected.imageset/icNavigateFeedSelected.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateHome.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateHomeSelected.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateHomeSelected.imageset/Frame 1321317525.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateHomeSelected.imageset/icNavigateHome.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateLibrary.imageset/icNavigateLibrary.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateLibrarySelected.imageset/icNavigateLibrarySelected.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateMy.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateMySelected.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateMySelected.imageset/icNavigateMySelected.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateMySelected.imageset/icNavigateMypageSelected.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateRecord.imageset/icNavigateRecord.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateRecordSelected.imageset/icNavigateRecordSelected.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateSearch.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateSearch.imageset/icNavigateSearch.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateSearchSelected.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Tabbar/icNavigateSearchSelected.imageset/icNavigateSearchSelected.svg
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
Labels: hyowon, reviewPlz

#142 [Design] #141 - 공용 컴포넌트 키워드 라벨 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Color/WSSPrimary100.colorset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icKeywordCancel.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icKeywordCancel.imageset/Frame 1000012022.svg
  WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/KeywordLink.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/KeywordManager.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/KeywordTag.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/KeywordLabel/keywordLabel.swift
Labels: naknak, reviewPlz

#147 [Design] #143 - HomeView UI 1차 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Recommend/RecommendService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Color/WSSGray20.colorset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Gradation/imgTodayPopularBackground.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Gradation/imgTodayPopularBackground.imageset/Frame 1321318279.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Gradation/imgTodayPopularBackground.imageset/Frame 1321318279@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Gradation/imgTodayPopularBackground.imageset/Frame 1321318279@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgTest2.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgTest2.imageset/Rectangle 1830.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgTest2.imageset/Rectangle 1830@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/imgTest2.imageset/Rectangle 1830@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Announcement/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Announcement/icAnnouncement.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Announcement/icAnnouncement.imageset/icAnnouncement.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Announcement/icAnnouncementDotted.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Announcement/icAnnouncementDotted.imageset/icAnnouncementDotted.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icBest.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icBest.imageset/icBest.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icBest.imageset/icBest@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icBest.imageset/icBest@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icCommasFinished.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icCommasFinished.imageset/icCommasFinished.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icCommasStarted.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icCommasStarted.imageset/icCommasStarted.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icComment.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icComment.imageset/icComment.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icHeart.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icHeart.imageset/icHeart.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icLikeDefault.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icLikeDefault.imageset/icLikeDefault.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icTextHot.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Other/icTextHot.imageset/icTextHot.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Star/icStar.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Star/icStar.imageset/icStar.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Star/icStar2.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/Star/icStar2.imageset/icStar2.svg
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIFont+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/RecommendResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeInterestView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeRealTimePopularFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeRealtimePopularView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickUserNumberChipView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeTasteRecommendView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeTodayPopularView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeInterestCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeSosoPickCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTasteRecommendCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeTodayPopularCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewModel/HomeViewModel.swift
Labels: chetseoo, reviewPlz

#155 [Setting] #153 - Trash 폴더 생성
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Trash/TrashView.swift
Labels: e-na, reviewPlz
