Repository Team-WSS/WSS-iOS, pull requests merged in 2024-01, with the labels that each got.

#2 [Setting] #1 - 초기세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/App/AppDelegate.swift
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Assets.xcassets/AccentColor.colorset/Contents.json
  WSSiOS/WSSiOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  WSSiOS/WSSiOS/Assets.xcassets/Contents.json
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Resource/Extensions/UIColor+.swift
  WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
Labels: jiwon

#3 [Setting] #1 - 추가 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  WSSiOS/WSSiOS/Assets.xcassets/AppIcon.appiconset/temporaryLogo.png
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Resource/Constants/Fonts/Pretendard-Bold.otf
  WSSiOS/WSSiOS/Resource/Constants/Fonts/Pretendard-Medium.otf
  WSSiOS/WSSiOS/Resource/Constants/Fonts/Pretendard-Regular.otf
  WSSiOS/WSSiOS/Resource/Constants/Fonts/Pretendard-SemiBold.otf
  WSSiOS/WSSiOS/Resource/Extensions/UIColor+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIFont+.swift
  WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
Labels: jiwon

#13 [Design] #12 - TabBar 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
Labels: e-na, reviewMore

#25 [DOCS] #20 - README 작성
  README.md
Labels: naknak, veryGoodDeveloper

#23 [Design] #11 - SearchView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icSearchCancel.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icSearchCancel.imageset/icSearchCancel.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample1.imageset/3.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample1.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample2.imageset/3-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample2.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample3.imageset/3-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample3.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample4.imageset/3-3.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample4.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample5.imageset/3-4.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample5.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample6.imageset/3-5.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample6.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIStackView+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIView+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchAssistantView/SearchEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchAssistantView/SearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchAssistantView/SearchResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchCell/SearchDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchCell/SearchTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/View/SearchView.swift
Labels: chetseoo, reviewPlz

#22 [Feat] #21 - 공통 메인버튼 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
Labels: e-na, veryGoodDeveloper

#26 [Fix] #20 - README 추가
  README.md
Labels: veryGoodDeveloper

#31 [Design] #27 - MyPageView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/임시 아바타-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/avaterExample.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/avaterExample.imageset/Rectangle 34626765.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeBL.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeBL.imageset/Property 1=icGenreBL.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeD.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeD.imageset/Property 1=icGenreD.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeF.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeF.imageset/Property 1=icGenreF.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeHF.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeHF.imageset/Property 1=icGenreHF.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeLN.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeLN.imageset/Property 1=icGenreLN.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeLogo.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeLogo.imageset/Property 1=default-2.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeMH.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeMH.imageset/Property 1=icGenreMH.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeMT.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeMT.imageset/Property 1=icGenreMT.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeR.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeR.imageset/Property 1=icGenreR.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeRF.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icBadge/badgeRF.imageset/Property 1=icGenreRF.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/icRight.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/icRight.imageset/ic_navigation_right.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/record.imageset/Component 3-2.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/record.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/register.imageset/Component 3.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icMyPage/register.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageSettingView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyReuseView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageViewModel.swift
Labels: e-na, reviewMore

#28 [Design] #24 - HomeView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLogoType.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLogoType.imageset/imgLogoType.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/render.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/render.imageset/render.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sample2.imageset/3-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sosopickCircle.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sosopickCircle.imageset/sosopickCircle.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sosopickSampleImage.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/sosopickSampleImage.imageset/sa.png
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIColor+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIFont+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSearchButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickUserNumberChipView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeSosoPickCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeSosoPickDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchView.swift
Labels: chetseoo, reviewMore

#33 [Feat] #27 - MyPageChangeNicknameView UI 및 기능 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/Contents.json
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageChangeNicknameView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
Labels: e-na, reviewPlz

#32 [Design] #15 - RegisterNormalView UI 50% 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalButtonGradientDummy.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalButtonGradientDummy.imageset/Frame 1321317569.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalGradientDummy.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalGradientDummy.imageset/Rectangle 41690 copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalGradientDummy.imageset/Rectangle 41690@2x copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalGradientDummy.imageset/Rectangle 41690@3x copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalNovelCover.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/RegisterNormalDummy/RegisterNormalNovelCover.imageset/IMG_5162.jpg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icCalendar.imageset/icCalendar.svg
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIImage+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UILabel+.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalVeiwModel/RegisterNormalViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalBannerImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalCustomToggleButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePickerButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDividerView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoWithRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformSelectButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalSectionTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalStarRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewModel/RegisterSuccessViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchEmptyView.swift
Labels: naknak, reviewMore

#34 [Design] #30 - NovelDetailView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Extensions/UIButton+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/LeftAlignedCollectionViewFlowLayout.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailCreateMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoGenreView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoKeywordView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailTabView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoKeywordCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoPlatformCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: hyowon, reviewPlz

#36 [Design] #29 - 기록뷰 UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/exampleAvater.imageset/exampleAvatar.png
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderAlignmentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
Labels: chetseoo, reviewMore

#38 [Design] #27 - ModalView UI 및 기능 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSMainButton.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageModalAvatarFeatureLabelView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCustomModalView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
Labels: e-na, reviewPlz

#42 [Setting] #40 - 레포지토리 패턴, 서버통신을 위한 폴더링 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Avatar/AvatarService.swift
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Network/Recommend/RecommendAPI.swift
  WSSiOS/WSSiOS/Network/Recommend/RecommendService.swift
  WSSiOS/WSSiOS/Network/User/UserAPI.swift
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/AvatarDTO.swift
  WSSiOS/WSSiOS/Source/Data/Repository/AvatarRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/MemoRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/RecommendRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserNovelRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/ViewController.swift
Labels: chetseoo, reviewPlz

#45 [Design] #15 - RegisterNormalView UI 구현 완료
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar@2x-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar@3x-1.png
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSSectionTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalKeywordSelectionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoWithRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalStarRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewMore

#52 [Design] #35 - MemoView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoCreateContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoCreateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoEditView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoCreateViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
Labels: hyowon

#49 [Design] #47- RegisterSuccess UI 구현 완료
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Lottie/animationRegistration.json
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewPlz

#51 [Setting] #46 - 네트워크 초기 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
  WSSiOS/WSSiOS/Network/Foundation/HTTPMethod.swift
  WSSiOS/WSSiOS/Network/Foundation/NetworkLogger.swift
  WSSiOS/WSSiOS/Network/Foundation/Networking.swift
  WSSiOS/WSSiOS/Network/Foundation/NetworkingServiceError.swift
  WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/Data+.swift
Labels: chetseoo, reviewPlz

#54 [Design] #43 - LibraryView UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryPageBar.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
Labels: e-na, reviewPlz

#59 [Setting] #58 - 네트워크 추가 세팅
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
  WSSiOS/WSSiOS/Network/Foundation/Networking.swift
Labels: chetseoo, reviewPlz

#62 [Network] #57 - NovelDetailView API 연결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserNovelResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserNovelRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoCreateViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoSettingButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: hyowon, reviewPlz

#60 [Feat] #48 - RegisterNormal 기능 80% 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalCustomDatePicker.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalCustomToggleButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePickerButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewPlz

#65 [Network] #63 - MemoView API 연결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Foundation/APIConstants.swift
  WSSiOS/WSSiOS/Network/Foundation/Networking.swift
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarEmpty.imageset/icStar-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarEmpty.imageset/icStar@2x-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarEmpty.imageset/icStar@3x-2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarFill.imageset/icStar.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarFill.imageset/icStar@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarFill.imageset/icStar@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/Frame 1321317558@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar@2x-1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icStar/icStarHalf.imageset/icStar@3x-1.png
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelMemoResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/MemoRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoCreateContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoReadContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoReadView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoCreateViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoSettingButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: hyowon, reviewPlz

#66 [Network] #37 - RecordView API 연결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Foundation/Networking.swift
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/DTO/MemoResult.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
Labels: chetseoo, veryGoodDeveloper

#70 [Feat] #21 - 공통 토스트 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icAlert/icAlertCheck.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icAlert/icAlertCheck.imageset/Group 1171275377.svg
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelMemoResult.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
Labels: hyowon, reviewPlz

#74 [Fix] #73 - 파일 수정
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageInfoViewController.swift
Labels: e-na, veryGoodDeveloper

#69 [Network] #61 - getUserNovelAPI 구현 완료
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgBackgroundGradient.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgBackgroundGradient.imageset/Rectangle 41690 copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgBackgroundGradient.imageset/Rectangle 41690@2x copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgBackgroundGradient.imageset/Rectangle 41690@3x copy.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingBackground.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingBackground.imageset/imgLoadingBackground.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingBackground.imageset/imgLoadingBackground@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingBackground.imageset/imgLoadingBackground@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingThumbnail.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingThumbnail.imageset/imgLoadingThumbnail.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingThumbnail.imageset/imgLoadingThumbnail@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/imgLoadingThumbnail.imageset/imgLoadingThumbnail@3x.png
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/Base/ReadStatus.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelResult.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserNovelResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserNovelRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalBannerImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalCustomDatePicker.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePickerButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoWithRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatFormTest.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalStarRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
Labels: naknak, reviewPlz

#77 [Feat] #71 - NovelDetail, Memo 세부 기능 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Extensions/UITextView+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToastView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupViewController/DeletePopupViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoEditContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoView/MemoAssistantView/MemoReadContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailCreateMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoGenreView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoKeywordView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoRatingView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailInfoReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailAssistantView/NovelDetailMemoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoKeywordCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailInfoPlatformCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailCell/NovelDetailMemoTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: hyowon, reviewPlz

#76 [Network] #68 - SearchView API 연결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/Novel/NovelService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/SearchResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
Labels: chetseoo, reviewPlz

#82 [Design] #79 - Home, Search, RecordView UI Detail 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterTagView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSearchButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeSosoPickCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeCell/HomeSosoPickDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchCell/SearchCollectionViewCell.swift
Labels: chetseoo, reviewPlz

#87 [Fix] #85 - 메모/정보 뷰 1차 QA 반영
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
Labels: hyowon, reviewPlz

#90 [Fix] #85 - 작품 등록 후 메모 남기기 버튼 클릭 시 메모 뷰로 이동
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: hyowon, reviewPlz

#92 [Fix] #91 - SearchView 1차 QA 반영
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchView/SearchAssistantView/SearchHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
Labels: chetseoo, reviewPlz

#95 [Fix] #89 - RegisterView 1차 QA 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Lotties/LottieLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Fonts/Pretendard-Bold.otf
  WSSiOS/WSSiOS/Resource/Fonts/Pretendard-Medium.otf
  WSSiOS/WSSiOS/Resource/Fonts/Pretendard-Regular.otf
  WSSiOS/WSSiOS/Resource/Fonts/Pretendard-SemiBold.otf
  WSSiOS/WSSiOS/Resource/Lottie/animationRegistration.json
  WSSiOS/WSSiOS/Resource/Lottie/regressorA.json
  WSSiOS/WSSiOS/Resource/Lottie/regressorB.json
  WSSiOS/WSSiOS/Resource/Lottie/scroll.json
  WSSiOS/WSSiOS/Resource/Lottie/sosocatA.json
  WSSiOS/WSSiOS/Resource/Lottie/sosocatB.json
  WSSiOS/WSSiOS/Resource/Lottie/villainessA.json
  WSSiOS/WSSiOS/Resource/Lottie/villainessB.json
  WSSiOS/WSSiOS/Source/Data/DTO/RecommendResult.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSearchButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalCustomDatePicker.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalDatePickerButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformSelectButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessView/RegisterSuccessView.swift
Labels: naknak

#96 [Fix] #94 - platform 버튼 사라진 것 수정, 네비게이션 바 아래의 DividerView 추가
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalNovelSummaryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalPlatformView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadDateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalAssistantView/RegisterNormalReadStatusView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalView/RegisterNormalView.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterNormal/RegisterNormalViewController/RegisterNormalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Register/RegisterSuccess/RegisterSuccessViewController/RegisterSuccessViewController.swift
Labels: naknak, reviewPlz

#97 [Fix] #86 - LibraryView 1차 QA 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/UserNovel/UserNovelService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icLibraryEmpty.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icLibraryEmpty.imageset/Frame 1321317486.svg
  WSSiOS/WSSiOS/Resource/Constants/Images/ImageLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryDummy.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
Labels: e-na, reviewPlz

#103 [Fix] #86 - 코드리뷰 반영 수정
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
Labels: e-na, veryGoodDeveloper

#101 [Fix] #99 - 데모데이 위한 자잘한 코드 수정
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/DeletePopup/DeletePopupView/DeletePopupAssistantView/DeletePopupContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
Labels: hyowon, reviewPlz

#104 [Fix] #93 - RecordView 1차 QA 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Network/Memo/MemoService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/MemoRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickTitleView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeSosoPickView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderAlignmentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordAssistantView/RecordHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
Labels: chetseoo, reviewPlz

#105 [Fix] #98 - MyPage 1차 QA 반영
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageModalAvatarFeatureLabelView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageTallyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageInventoryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageSettingCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCustomModalView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageCustomModalViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageViewModel.swift
Labels: e-na, reviewPlz

#107 [Fix] #99 - Library, MyPageView Detail 수정
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/LaunchScreen.storyboard
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryBaseViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Memo/MemoViewController/MemoReadViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/SearchViewController/SearchViewController.swift
Labels: e-na, reviewPlz

#108 [Fix] #99 - 1.5차 QA 결과 반영
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordViewController/RecordViewController.swift
Labels: naknak, reviewPlz

#110 [Fix] #99 - Mypage Navigation 배경 변경, 기기대응 추가
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeAssistantView/HomeCharacterView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeView/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Record/RecordView/RecordCell/RecordTableViewCell.swift
Labels: naknak, e-na, veryGoodDeveloper
