Repository Team-WSS/WSS-iOS, pull requests merged in 2025-05, with the labels that each got.

#536 [Chore] #534 - StringLiterals Extension 활용파여 파일 분리
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Feed.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Home.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+MyPage.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Novel.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Onboarding.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Search.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageSettingViewController.swift
Labels: guryss, reviewPlz

#538 [Fix] #537 - 일반 탐색 결과 레이아웃 깨지는 문제 해결
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchResultCountView.swift
Labels: haku, reviewPlz

#533 [Feat] #521 - 피드 비공개 설정 UI 및 서버 로직 구현
  WSSiOS/WSSiOS/Network/FeedService.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/icLock.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/icLock.imageset/icLock.svg
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/icPhoto.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/icon/icPhoto.imageset/icImage.svg
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Feed.swift
  WSSiOS/WSSiOS/Source/Data/DTO/Feed/FeedResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/MyFeedListResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/TotalFeedListResponse.swift
  WSSiOS/WSSiOS/Source/Data/Entity/Feed/FeedEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/MyFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/TotalFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedDetailRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListPrivateView.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedCell/FeedPageBarCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedPageBar.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditCategoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentSpoilerView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditNovelConnectView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditPrivateSettingView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditViewController/FeedEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditViewModel/FeedEditViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedCell/FeedListTableViewCell.swift
Labels: guryss, reviewPlz

#543 [Chore] #541 - 피드작성뷰 내 이미지 추가 버튼 코드 주석 처리
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
Labels: guryss, reviewPlz

#552 [Hotfix] #551 - 댓글 잘려서 보이는 이슈 해결
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
Labels: guryss, reviewPlz

#555 최신 Release Branch를 Develop Branch에 병합
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
Labels: guryss, neverStopGrowing

#550 [Chore] #544 - auto assignee 설정
  .github/auto_assign.yml
Labels: guryss, reviewPlz

#539 [FIx] #515 - 댓글 작성 중복 요청 방지 로직 추가
  WSSiOS/WSSiOS/Resource/Constants/NotificationCenter/NotificationName.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailUnknownFeedErrorViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
Labels: guryss, reviewPlz

#557 [Feat] #553 - 피드 목록 및 마이페이지 피드 이미지 첨부 UI 구현
  WSSiOS/WSSiOS/Resource/Assets.xcassets/testImage.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/testImage.imageset/testImage.jpg
  WSSiOS/WSSiOS/Source/Data/Entity/MyFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/TotalFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListTableViewCell.swift
Labels: guryss, reviewPlz

#559 [Chore] #558 - 온보딩과 마이페이지의 URL 링크 수정
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/ServiceTermAgreement/ServiceTerm.swift
Labels: e-na, reviewPlz

#561 [Refactor] #560 - DTO-Entity 분리 및 최신 컨벤션 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/User/BlocksService.swift
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/User/UserInfoResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/User/UserNovelListResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/User/UserNovelStatusResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/User/UserPreferencesResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserInfoResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/ProfileEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserInfoEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserNovelListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserNovelStatusEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserPreferenceEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository/UserInfoRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageAssistantView/MyPageCountView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageCell/MyPageEditProfileGenreCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageChangeNicknameView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageView/MyPageEditProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageChangeNicknameViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageEditProfileViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/MyPageViewModel/MyPageEditProfileViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageGenrePreferencesTopView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageGenrePreferencesView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPagePreferencesEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageProfileHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileCell/MyPageGenrePreferencesOtherTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageDeleteIDWarningView.swift
Labels: e-na, reviewMore

#568 [Fix] #567- 파일 삭제
  WSSiOS/WSSiOS/GoogleService-Info-Debug.plist
  WSSiOS/WSSiOS/GoogleService-Info.plist
Labels: e-na, neverStopGrowing

#563 [Feat] #556 - 피드 상세뷰 내 이미지 첨부 UI 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Resource/Helper/ModuleFactory.swift
  WSSiOS/WSSiOS/Source/Data/DTO/Feed/FeedResponse.swift
  WSSiOS/WSSiOS/Source/Data/Entity/Feed/FeedEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedDetailRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAddImageViewerView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailAddImageView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailAddImageViewerCell.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailAddImageViewerController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
Labels: guryss, reviewPlz
