Repository Team-WSS/WSS-iOS, pull requests merged in 2025-02, with the labels that each got.

#470 [Fix] #469 - 공지사항 내 화면 전환 시 메인 스레드에서 동작하도록 수정
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewController/HomeNoticeViewController.swift
Labels: guryss, reviewPlz

#483 [Fix] #481 - 공지사항 무한스크롤 작동되지 않는 이슈 해결
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotification/HomeNotificationViewModel/HomeNotificationViewModel.swift
Labels: guryss, reviewPlz

#487 [Refactor] #485 - DTO, Entity 분리 적용, VM, VC 정리
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Auth/AuthService.swift
  WSSiOS/WSSiOS/Network/Foundation/TokenCheckURLProtocol.swift
  WSSiOS/WSSiOS/Network/NovelDetail/NovelDetailService.swift
  WSSiOS/WSSiOS/Network/Onboarding/OnboardingService.swift
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Data/Base/ReadStatus.swift
  WSSiOS/WSSiOS/Source/Data/DTO/AuthResult.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelDetailHeaderResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelDetailInfoResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/OnboardingResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserInfoResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NovelDetailHeaderEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NovelDetailInfoEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/AuthRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelDetailRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/OnboardingRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileCell/MyPageNovelPreferencesCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailHeaderView/NovelDetailHeaderAssistantView/NovelDetailHeaderNovelInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailHeaderView/NovelDetailHeaderAssistantView/NovelDetailHeaderReadStatusButton.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailHeaderView/NovelDetailHeaderAssistantView/NovelDetailHeaderReviewResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoAssistantView/NovelDetailInfoDescriptionView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoAssistantView/NovelDetailInfoReviewAttractivePointView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoAssistantView/NovelDetailInfoReviewGraphStackView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoAssistantView/NovelDetailInfoReviewGraphView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoAssistantView/NovelDetailInfoReviewView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoCell/NovelDetailInfoPlatformCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoCell/NovelDetailInfoReviewKeywordCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailInfoView/NovelDetailInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewModel/NovelDetailViewModel.swift
Labels: nagi, reviewPlz

#488 [Release] 1.1.0 업데이트 준비
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
Labels: e-na, veryGoodDeveloper
