Repository Team-WSS/WSS-iOS, pull requests merged in 2025-03, with the labels that each got.

#496 [Refactor] #495 - Feed 로직 DTO -> Entity 변환
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/FeedDetailService.swift
  WSSiOS/WSSiOS/Network/FeedService.swift
  WSSiOS/WSSiOS/Network/NovelDetail/NovelDetailService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NovelDetailFeedResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/TotalFeedListResponse.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NovelDetail/NovelDetailFeedEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NovelDetail/NovelDetailHeaderEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NovelDetail/NovelDetailInfoEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/TotalFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NovelDetailRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListCategoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedView/FeedCell/FeedCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedGenreViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewModel/FeedGenreViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewModel/FeedViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedCell/FeedListTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewModel/NovelDetailViewModel.swift
Labels: e-na, reviewPlz

#497 [Refactor] #495 - Library 로직 DTO -> Entity 변환
  WSSiOS/WSSiOS/Network/User/UserService.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserNovelListResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserNovelListResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/UserNovelListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryAssistantView/LibraryListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryCell/LibraryTabCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryChildView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryView/LibraryPageBar.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryChildViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryChildViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryViewModel.swift
Labels: e-na, reviewPlz

#500 [Refactor] #495 - MyPage/Setting/Setting/ProfileVisibility & Info 로직 DTO -> Entity 변환 및 수정
  WSSiOS/WSSiOS/Network/UserService.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/MyProfileResult.swift
  WSSiOS/WSSiOS/Source/Data/DTO/UserInfoResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserInfoEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/User/UserNovelEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/AuthRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository/UserInfoRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageChangeUserInfoView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageSettingView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageDeleteIDWarningViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageProfileVisibilityViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageSettingViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageInfoViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageProfileVisibilityViewModel.swift
Labels: e-na, reviewPlz

#501 [Refactor] #495 - MyPage/Setting/Setting/ChangeUserInfo & DeleteID & PushNotification 로직 DTO -> Entity 변환 및 수정
  WSSiOS/WSSiOS/Network/Auth/AuthService.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/AuthResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/AuthRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageChangeUserInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageDeleteIDViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPagePushNotificationViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageChangeUserInfoViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageDeleteIDViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPagePushNotificationViewModel.swift
Labels: e-na, reviewPlz

#508 [Chore] #507 - Notification 네이밍 반영 및 Home 폴더 Folder로 변경
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeSearchButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularContentTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotificationDetail/HomeNotificationDetailView/HomeNotificationDetailAssistantView/HomeNotificationDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotificationDetail/HomeNotificationDetailView/HomeNotificationDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotificationDetail/HomeNotificationDetailViewController/HomeNotificationDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotificationDetail/HomeNotificationDetailViewModel/HomeNotificationDetailViewModel.swift
Labels: guryss, reviewPlz

#514 [Refactor] #509 - 피드상세 DTO-Entity 구조 반영
  WSSiOS/WSSiOS/Network/FeedDetailService.swift
  WSSiOS/WSSiOS/Source/Data/DTO/Feed/FeedRequest.swift
  WSSiOS/WSSiOS/Source/Data/DTO/Feed/FeedResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/FeedDetailResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/Feed/FeedCommentEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/Feed/FeedEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/FeedDetailRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditViewModel/FeedEditViewModel.swift
Labels: guryss, reviewPlz

#517 [Fix] #498 - 피드 길이가 길어질 때 마지막 2개의 댓글이 잘리는 이슈 해결
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyView.swift
Labels: guryss, reviewPlz

#513 [Feat] #512 - 수다 → 피드 UX라이팅 변경
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Amplitude/AmplitudeEvent.swift
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/Frame 1321318328.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/Frame 1321318328@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/Frame 1321318328@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/device=ios, status=1.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/device=ios, status=1@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner1.imageset/device=ios, status=1@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/Frame 1321318588.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/Frame 1321318588@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/Frame 1321318588@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/device=ios, status=2.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/device=ios, status=2@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner2.imageset/device=ios, status=2@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/Frame 1321318589.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/Frame 1321318589@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/Frame 1321318589@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/device=ios, status=3.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/device=ios, status=3@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner3.imageset/device=ios, status=3@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/Contents.json
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/Frame 1321318482.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/Frame 1321318482@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/Frame 1321318482@3x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/device=ios, status=4.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/device=ios, status=4@2x.png
  WSSiOS/WSSiOS/Resource/Assets.xcassets/Image/Onboarding/imgLoginBanner4.imageset/device=ios, status=4@3x.png
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
Labels: haku, reviewPlz

#505 [Refactor] #495 - MyPage/Profile/EditAvatar & EditProfile & FeedDetail 로직 DTO -> Entity 변환 및 수정
  WSSiOS/WSSiOS/Network/Avatar/AvatarService.swift
  WSSiOS/WSSiOS/Network/UserService.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/AvatarResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/MyFeedListResponse.swift
  WSSiOS/WSSiOS/Source/Data/DTO/MyProfileResponse.swift
  WSSiOS/WSSiOS/Source/Data/Entity/AvatarEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/MyFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/ProfileEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/AvatarRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/UserRepository/UserInfoRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedGenreViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailReplyWritingView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryChildViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageEditAvatarView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageEditProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageProfileHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageEditAvatarViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageEditProfileViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageEditAvatarViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageEditProfileViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageFeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedCell/FeedListTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchResultViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
Labels: e-na, reviewPlz

#518 [Fix] #495 - MyPage 에러 해결
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
Labels: e-na, neverStopGrowing
