Repository Team-WSS/WSS-iOS, pull requests merged in 2025-08, with the labels that each got.

#614 [Feat] #613 - 1.3.0 업데이트를 위한 기획 수정 사항 반영
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+Feed.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals+MyLibrary.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/Feed/FeedView/FeedAssistantView/FeedEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/Feed/FeedView/FeedPageContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/Feed/FeedViewController/FeedPageContentViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/MyLibrary/MyLibraryView/MyLibraryAssistantView/MyLibraryEmptyView.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/MyLibrary/MyLibraryView/MyLibraryView.swift
Labels: e-na, veryGoodDeveloper

#612 [Feat] #611 - 1초 간 스플래시 뷰 보여지고 앱 전환 기능 적용
  WSSiOS/WSSiOS/App/SceneDelegate.swift
  WSSiOS/WSSiOS/Source/Presentation/Splash/SplashView.swift
  WSSiOS/WSSiOS/Source/Presentation/Splash/SplashViewController.swift
Labels: guryss, reviewPlz

#615 [Fix] #613 - 문의하기 URL 수정 및 외부링크 분리
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/URLs/ExternalLinks.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelKeywordSelectModalViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchResultViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/UserPage/MyPage/MyPageSetting/MyPageSettingViewController/MyPageSettingViewController.swift
Labels: e-na, reviewPlz

#617 [Fix] #616 - 타 유저 피드 내 썸네일 이미지 안보임 이슈 | 타 유저 피드 상세 내 데이터 중복 호출 이슈
  WSSiOS/WSSiOS/Source/Data/Entity/Feed/TotalFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Data/Entity/UserFeedListEntity.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/UserPage/UserPage/UserPageViewModel/UserPageFeedDetailViewModel.swift
Labels: guryss, reviewPlz
