Repository Team-WSS/WSS-iOS, pull requests merged in 2025-04, with the labels that each got.

#524 [Fix] #519 - QA사항 반영. My 탭과 서재 탭의 라이팅 변경
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
Labels: nagi, veryGoodDeveloper

#528 [Feat] #527 - 프로필 비공개 설정 토글 형식으로 변경
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPageProfileVisibilityView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageProfileVisibilityViewController.swift
Labels: haku, reviewPlz

#526 [Feat] #525 - 작품 문의하러 가기 추가
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchView/DetailSearchAssistantView/DetailSearchResultNovelView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchResultViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchResultCountView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchView/NormalAssistantView/NormalSearchResultView.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewController/NormalSearchViewController.swift
Labels: haku, reviewPlz

#530 [Fix] #529 - 타인 보관함을 보려고 해도 본인의 서재 탭으로 이동하는 오류 해결
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
Labels: nagi, reviewPlz
