Repository Team-WSS/WSS-iOS, pull requests merged in 2025-01, with the labels that each got.

#398 [Fix] #397 - 소소픽 데이터 조회 실시간 반영되도록 수정
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewModel/SearchViewModel.swift
Labels: guryss, reviewPlz

#402 [Fix] #376 - 삭제된 글 클릭 시 모달 Alert 기능 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailUnknownUserErrorView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailUnknownUserErrorViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchViewController.swift
Labels: guryss, reviewPlz

#410 [Fix] #408 - MyPage 피드 카테고리 뒤에서부터 5개가 뜨는 에러 해결
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
Labels: e-na, reviewPlz

#407 [Feat] #376 - MyPageEditView 진입 분기처리 및 장르 미선택시 에러 해결
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageEditProfileViewModel.swift
Labels: e-na, reviewPlz

#406 [Feat] #403 - 앰플리튜드 도입
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Resource/Amplitude/AmplitudeEvent.swift
  WSSiOS/WSSiOS/Resource/Amplitude/AmplitudeManager.swift
  WSSiOS/WSSiOS/Resource/Constants/Config/Config.swift
  WSSiOS/WSSiOS/Source/Data/Base/NovelGenre.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedGenreViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewModel/FeedGenreViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewModel/FeedViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewController/FeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditViewController/FeedEditViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditViewModel/FeedEditViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeCell/HomeRealtimePopularCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Login/LoginViewModel/LoginViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageInfoViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageDeleteIDViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewModel/NovelDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelKeywordSelectModalViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelReview/NovelReviewViewModel/NovelReviewViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewController/DetailSearchResultViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/DetailSearch/DetailSearchViewModel/DetailSearchResultViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/NormalSearch/NormalSearchViewModel/NormalSearchViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewController/SearchViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Search/Search/SearchViewModel/SearchViewModel.swift
Labels: haku, reviewPlz

#443 [Fix] #438 - Issue Template 수정
  .github/ISSUE_TEMPLATE/✨-버그-발견.md
  .github/ISSUE_TEMPLATE/✨-새로운-기능-.md
Labels: e-na, veryGoodDeveloper

#433 [Fix] #411 - FeedEditView 이모지 깨지는 문제 해결
  WSSiOS/WSSiOS/Source/Presentation/FeedEdit/FeedEditView/FeedEditAssistantView/FeedEditContentView.swift
Labels: haku, reviewPlz

#437 [Fix] #425 - MyPageFeedDetail 에러 수정
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
Labels: e-na, reviewPlz

#442 [Fix] #441 - 로그아웃시 데이터 남아있는 에러 수정
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageDeleteIDViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPageInfoViewModel.swift
Labels: e-na, reviewPlz

#450 [Fix] #429 -2 - 네비게이션 바가 화면 전환 시 뒤늦게 사라지는 오류 수정
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
Labels: nagi, reviewPlz

#446 [Fix] #444 - NovelDetailFeedListView 공용컴포넌트로 수정
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListCategoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListConnectedNovelView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListReactView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListView.swift
  WSSiOS/WSSiOS/Source/Presentation/Feed/FeedViewController/FeedGenreViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageStickyHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageFeedDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedCell/FeedListTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailView/NovelDetailFeedView/NovelDetailFeedView.swift
  WSSiOS/WSSiOS/Source/Presentation/NovelDetail/NovelDetailViewController/NovelDetailViewController.swift
Labels: e-na, reviewMore

#458 [Fix] #457 - MyPageFeedView 오탈자 수정
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/MyPageFeedView.swift
Labels: e-na, veryGoodDeveloper

#447 [Feat] #432 - 공지사항 전체 및 상세 조회 API 구현
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS/Network/Notice/NoticeService.swift
  WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIImageView+.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NoticeResult.swift
  WSSiOS/WSSiOS/Source/Data/Entity/NotificationEntity.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NoticeRepository.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeView/HomeNoticeCell/HomeNoticeTableViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeView/HomeNoticeView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewController/HomeNoticeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewModel/HomeNoticeViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailView/HomeNoticeDetailAssistantView/HomeNoticeDetailContentView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailView/HomeNoticeDetailView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailViewController/HomeNoticeDetailViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNoticeDetail/HomeNoticeDetailViewModel/HomeNoticeDetailViewModel.swift
Labels: guryss, reviewMore

#455 [Chore] #448 - 숨겨진 글 및 차단 유저의 글 팝업 분기처리 추가 | 탈퇴 유저 이름 분기처리 제거
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/FeedList/FeedListHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailAssistantView/FeedDetailProfileView.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailView/FeedDetailCell/FeedDetailReplyCollectionViewCell.swift
  WSSiOS/WSSiOS/Source/Presentation/FeedDetail/FeedDetailViewModel/FeedDetailViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageProfileHeaderView.swift
Labels: guryss, reviewPlz

#464 [Setting] #463 - Debug 버전 앱 세팅
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/xcshareddata/xcschemes/WSSiOS.xcscheme
Labels: e-na, reviewPlz

#452 [Feat] #451 - 보관함 상태 탭시 특정 위치로 이동 및 에러 수정
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewController/LibraryViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Library/LibraryViewModel/LibraryViewModel.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileView/ProfileAssistantView/MyPageInventoryView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewModel/MyPageViewModel.swift
Labels: e-na, reviewPlz

#449 [Feat] #445 - 비열람 알림 존재 여부 조회 API 연결 구현
  WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Data/DTO/NoticeResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSTabBarItem.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeView/HomeAssistantView/HomeHeaderView.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewModel/HomeViewModel.swift
Labels: guryss, reviewPlz

#467 [Feat] #466 - 피드 관련 공지사항 알림 읽음 처리 API 구현
  WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/HomeNotice/HomeNoticeViewModel/HomeNoticeViewModel.swift
Labels: guryss, reviewPlz

#465 [Feat] #434 - 푸시알림 수신 및 탭 하면 화면이동 기능 구현
  .gitignore
  WSSiOS/WSSiOS.xcodeproj/project.pbxproj
  WSSiOS/WSSiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WSSiOS/WSSiOS/App/AppDelegate.swift
  WSSiOS/WSSiOS/Info.plist
  WSSiOS/WSSiOS/Network/Notification/NotificationService.swift
  WSSiOS/WSSiOS/Resource/Constants/Strings/StringLiterals.swift
  WSSiOS/WSSiOS/Resource/Constants/URLs/URLs.swift
  WSSiOS/WSSiOS/Resource/Extensions/UIViewController+.swift
  WSSiOS/WSSiOS/Resource/Helper/KeychainHelper.swift
  WSSiOS/WSSiOS/Resource/Helper/NotificationHelper.swift
  WSSiOS/WSSiOS/Source/Data/DTO/PushNotificationResult.swift
  WSSiOS/WSSiOS/Source/Data/Repository/NotificationRepository.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/AlertButton/WSSAlertButtonView.swift
  WSSiOS/WSSiOS/Source/Presentation/Base/WSSToggleButton.swift
  WSSiOS/WSSiOS/Source/Presentation/Home/Home/HomeViewController/HomeViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Profile/ProfileViewController/MyPageViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingView/MyPagePushNotificationView.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPagePushNotificationViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewController/MyPageSettingViewController.swift
  WSSiOS/WSSiOS/Source/Presentation/MyPage/Setting/SettingViewModel/MyPagePushNotificationViewModel.swift
  WSSiOS/WSSiOS/WSSiOS.entitlements
Labels: nagi, reviewPlz
